version: '3.4'
services:
  fileserver:
    image: fileserver
    build:
      context: .
      dockerfile: ./fileserver/Dockerfile
    hostname: fileserver
    networks:
      - dmz
    ports:
      - 443:55443
    volumes:
      - fs-suite:/home/fileserver
      - fs-data:/var/fileserver
  link-manager:
    image: link-manager
    build:
      context: .
      dockerfile: ./link-manager/Dockerfile
    networks:
      - isolated
    hostname: link-manager
    ports:
      - 8080:80
    volumes:
      - fs-suite:/home/fileserver
  # certbot:
  #   image: certbot
  #   build:
  #     context: .
  #     dockerfile: ./certbot/Dockerfile
  #   ports:
  #     - 55433:55433
  #   volumes:
  #     - fs-suite:/home/node/app
volumes:
  fs-suite:
    # Recommended to utilize a fast, local volume for DB
  fs-data:
    # Recommended to attach to NFS/CIFS for this volume
  fs-certs:
    # PrivKey and PubCert/FullChain location; NFS/CIFS recommended if utilizing host to attain certs
networks:
  dmz:
    name: custom_dmz
    driver: bridge
  isolated:
    name: custom_isolated
    driver: bridge
